# Docker Compose for DuckDB Testing
# Production runs everything embedded - no Docker needed!

services:
  # DuckDB Server for Testing (when native module fails in test environment)
  duckdb:
    build:
      context: ./docker/duckdb
      dockerfile: Dockerfile
    container_name: guru-duckdb
    restart: unless-stopped
    ports:
      - "8080:8080"   # HTTP API for test environment
    volumes:
      - duckdb_data:/data
    environment:
      - DUCKDB_PATH=/data/analytics.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  duckdb_data:
    driver: local